### ISSUE TITLE
본문 정렬을 적용했을 때 정상적으로 작동하지 않는 요소들이 있습니다.

### ISSUE THREAD

**Issue by kugorang** [wisdomstar94/torytis-tistory-skin-stroke#1]
- [x] 카카오톡 이모티콘
- [x] Youtube 동영상 (하이퍼링크 입력 시 자동 추가, Tistory 플러그인으로 추가)

**Comment by wisdomstar94** [comment]
이슈 남겨주셔서 감사합니다.
혹시 해당 현상이 발생하는 화면을 캡쳐해서 올려주실 수 있으실까요?

그리고 해당 현상을 재현하기 위한 방법도 추가로 작성해주시면 감사하겠습니다.

**Comment by kugorang** [comment]
우선 정정할 사항이 있습니다. 이모지가 아닌 티스토리 본문에서 사용 가능한 카카오톡 이모티콘을 말씀드렸는데, 이모지로 잘못 표기했습니다. 이전 이슈 내용도 수정해두겠습니다.

![스크린샷 2023-12-25 12 30 59](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/assets/12571114/e2f07690-a712-4707-98c4-3e8ca97b873a)

글 작성 시에, 티스토리에서 제공하는 카카오톡 이모티콘을 선택하시면 바로 적용 가능합니다.

![스크린샷 2023-12-25 12 32 40](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/assets/12571114/e22342bd-4d98-4950-876f-41083493a850)

이모티콘의 정렬을 가운데로 설정했으나,

![스크린샷 2023-12-25 12 53 41](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/assets/12571114/d1b1d17e-0cb2-47cd-a169-c5f3fa83aeb2)

실제로는 왼쪽 정렬로 표기됩니다. 블로그 글은 https://kugorang.tistory.com/20 에서 확인 가능합니다.


두 번째로 유튜브 영상입니다.

![스크린샷 2023-12-25 12 47 24](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/assets/12571114/73f585c3-5684-406c-9863-ec8120a6d0d4)
![스크린샷 2023-12-25 12 48 57](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/assets/12571114/04717486-cabd-4562-a093-2f6dc9840ba9)

Youtube 동영상을 오른쪽 정렬을 지정한 후 글을 작성했습니다.

![스크린샷 2023-12-25 12 49 40](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/assets/12571114/2891b616-e9ee-4e17-a41c-2c0cf7007678)

현재 티스토리에 Youtube 동영상을 첨부하는 방식이 두 가지로 알고 있는데, 하나는 글을 작성할 때 링크를 입력하면 자동으로 import 되는 방식이고, 다른 하나는 티스토리에서 제공하는 Youtube 동영상 플러그인을 활용한 동영상 추가로 알고 있습니다.

![스크린샷 2023-12-25 12 52 41](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/assets/12571114/7495dff0-db20-4ca8-88f0-b631ddea7b0b)

이 역시, 이모티콘과 마찬가지로 정렬이 제대로 작동하지 않습니다. 블로그 글은 https://kugorang.tistory.com/21 에서 확인 가능합니다.


확인 부탁드리겠습니다. 감사합니다.

**Comment by wisdomstar94** [comment]
상세한 설명 감사합니다.
말씀 주신 현상들은 v1.1.3 에서 수정되었습니다.
v1.1.3 으로 업데이트 하신 상태에서 확인 후 여전히 동일한 현상이 발생하면 말씀 부탁드리며,
만약 이상 없을 경우 본 이슈는 close 하도록 하겠습니다.

**Comment by kugorang** [comment]
안녕하세요, 해당 이슈가 v1.1.13에서 수정된 것을 확인했습니다.

다만, 이슈 수정으로 인해 #4 이슈가 발생한 듯 하여 이 부분이 버그인지 확인 부탁드리겠습니다.

감사합니다.
