### ISSUE TITLE
개인 도메인 설정 시, 블로그 주인으로 인식 못 하는 문제

### ISSUE THREAD

**Issue by kugorang** [wisdomstar94/torytis-tistory-skin-stroke#10]
안녕하세요, 제작자님. 오늘 티스토리 블로그에 개인 도메인을 적용했을 때, 상단에 글쓴이만 볼 수 있는 메뉴가 표시 되지 않아 스킨에서 발생한 버그인지 문의드립니다.

아래 스크린샷은 티스토리 URL로 접속한 화면입니다. (https://kugorang.tistory.com/25)

![스크린샷 2023-12-26 15 32 20](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/assets/12571114/868b1ba0-db1a-47b5-97e9-289d5cfd30fa)

아래 스크린샷은 개인 도메인 URL로 접속한 화면입니다. (https://kugora.ng/25)

![스크린샷 2023-12-26 15 32 38](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/assets/12571114/e2a833d4-5527-458a-8300-0ee621fb8190)

확인 부탁드리겠습니다. 감사합니다.

**Comment by wisdomstar94** [comment]
안녕하세요.

해당 메뉴는 아래 사진처럼 [티스토리 스킨 가이드 문서](https://tistory.github.io/document-tistory-skin/contents/post.html)에 나와 있는 <s_ad_div> 치환자 태그를 사용한 부분입니다.
![image](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/assets/93423564/d88920ac-386c-402b-a5d2-47be2b850bcd)


tistory.com 도메인일 경우에는 정상 작동하지만 타 도메인일 경우에는 티스토리 측에서 해당 치환자가 동작하지 않는 것으로 보여지네요. :(

관리자를 체크하지 않고 상시 보여지게 하는 스킨 옵션을 추가하는 방법이 대책이 될 수 있을 것 같기도 하네요. (다만 이렇게 되면 블로그 소유자가 아니더라도 모든 방문자들에게 해당 메뉴들이 보여지게 되긴 할겁니다.)

**Comment by wisdomstar94** [comment]
아니면, 치환자 태그를 사용하지 않고 다른 방법으로 블로그 소유자를 체크하는 루트가 존재하는데..
이 루트를 사용가능한지 확인하려면 한가지 확인을 요청드릴 부분이 있습니다.

티스토리 로그인 되어 있으신 상태에서 타 도메인(말씀하신 https://kugora.ng 도메인)으로 블로그 홈에 접근하신 후
개발자도구의 콘솔창에서 window.tiara.customProps 을 입력했을 때 나오는 정보를 확인해주실 수 있으실까요?

**Comment by kugorang** [comment]
안녕하세요, 로그인 된 상태에서 티스토리 도메인과 개인 도메인일 때의 결과를 각각 보내드립니다.

- 티스토리 도메인: {userId: '564310', blogId: '720965', entryId: 'null', role: 'owner', trackPage: '홈_보기', …}
- 개인 도메인: {userId: '0', blogId: '720965', entryId: 'null', role: 'guest', trackPage: '홈_보기', …}

도움이 되셨으면 좋겠습니다!

**Comment by wisdomstar94** [comment]
안녕하세요. 확인 감사합니다. 😀

올려주신 내용을 보아하니 개인 도메인에서는 
티스토리에서 로그인 되어 있지 않은 상태라고 처리되어 지는 것 같네요. 😢

**Comment by kugorang** [comment]
그렇군요 ㅠㅠ 해결 방법이 없다면 해당 이슈는 티스토리 버그라고 생각되네요. 해결하기 어려우면 바로 닫아주셔도 될 것 같습니다.

의견이 있다면 스킨 편집창에 개인 도메인 입력을 받게 하고, 해당 도메인으로 접근 시 편집에 저장된 개인 도메인과 일치하면 나를 'owner' 로 판단하고 코드 작성을 하는 건 어려울까요?

**Comment by wisdomstar94** [comment]
그렇게 될 경우 그 개인 도메인으로 방문하는 모든 사람들이 "owner" 로 처리 될 겁니다. (꼭 블로그 소유자가 아니더라도 제 3자도 개인 도메인으로 접근 가능하기 때문)
즉, 블로그 소유자를 판별 하지는 못합니다.

판별하지는 못하지만, 
말씀하신 의도가 **특정 도메인으로 접근이 되었을 때는 로그인 유무 상관없이 항상 관리자메뉴가 표시되게 하는 것**을 의도하신 거라면
그렇게 작업이 가능하긴 합니다.

**Comment by kugorang** [comment]
아, 저는 {userId: '564310', blogId: '720965', ... , role: 'owner', ,,,} 의 값과 스킨 편집의 설정에 적힌 개인 도메인을 활용하면 이 블로그는 내 것임을 인증할 수 있겠다라는 생각을 했습니다.

정확히 다시 말씀드리면 "blogId: '720965'" 라는 값을 활용하고 싶었는데, 이 값이 웹 브라우저에서 캐싱이 가능할 거라 생각했었습니다. 현재 role: 'owner'일 때 내 blogId가 비어 있다면 프론트 쪽에서 blogId를 저장합니다.

이후 다른 도메인으로 들어왔을 때 blogId가 존재하고, 해당 도메인이 미리 입력해둔 개인 도메인일 경우 블로그 주인으로 판단하는 것을 생각했습니다.


위의 글을 적으며 두 가지 문제를 추가적으로 생각해봤습니다.

1. 티스토리 스킨에서 데이터 캐싱이 가능한가?
2. 보안 상의 문제는 없는가? (티스토리 정책 위반이 아닐까?)

이 부분은 저보다 스킨 제작자님께서 더 잘 아실거라 생각되어 여기까지만 댓글 남기겠습니다. (애초에 티스토리 버그인 거 같긴 한데 ㅠㅠ)

**Comment by wisdomstar94** [comment]
저장은 로컬스토리지나 쿠키를 활용하는 방법이 있겠지만,
이는 동일 도메인에 제한됩니다.

즉, *.tistory.com 도메인에서 쿠키나 로컬스토리지에 저장한 데이터를
다른 도메인에서 참조할 수 없기 때문에.. 의견주신 방법은 어렵지 않을까 생각됩니다. 😥

**Comment by kugorang** [comment]
안녕하세요, 우선 웹 관련 지식이 짧아 죄송하다는 말씀부터 드립니다. 브라우저 자체에 저장을 하는 localStorage 개념이면 되지 않을까 싶은 생각이 들었는데, 웹 브라우저가 거기까지 지원을 해주지 않나 보네요 ㅠㅠ

저는 더 이상 좋은 방법이 없네요 😥 아쉽지만 제작자님께서도 더 의견이 없으시면 이슈 닫아주시거나 이후에 다시 논의 부탁드리겠습니다!

**Comment by wisdomstar94** [comment]
넵, 우선 본 이슈는 닫도록 하고 저도 더 좋은 방법이 없을까 고민을 좀 해봐야겠네요~ 수고하셨습니다.
