### ISSUE TITLE
복사 붙여넣기한 코드가 다크모드에서 제대로 표시되지 않는 문제

### ISSUE THREAD

**Issue by kugorang** [wisdomstar94/torytis-tistory-skin-stroke#16]
안녕하세요, v1.1.22 버전을 사용하던 중 버그가 발견되어 리포트 남겨 놓습니다.

# Issue 내용

- Github에 있던 코드를 Tistory에 붙여 넣었을 때 코드 블럭이 다크모드로 표시되지 않고 화이트모드로 표시됩니다.
- Github에 있던 코드는 https://github.com/KraftonJungle4th/Classroom4_Week02_Team7_StudyNotes/issues/1#issuecomment-1899930818 입니다.
- Tistory의 블로그 글은 https://kugora.ng/33 입니다.

# 기타

- 티스토리에서 직접 코드 블럭으로 추가한 경우엔 다크모드와 화이트모드 변경이 잘 됩니다. (Tistory 블로그 글의 가장 아래 코드를 확인해주세요.)

**Comment by wisdomstar94** [comment]
안녕하세요. 이슈 남겨주셔서 감사합니다.
남겨주신 이슈는 https://github.com/wisdomstar94/torytis-tistory-skin-stroke/releases/tag/v1.1.24
에서 수정되었으니 확인 부탁드립니다.

**Comment by kugorang** [comment]
안녕하세요, 해당 이슈가 v1.1.25 기준으로 수정 완료된 것으로 확인되어 댓글 남겨 놓습니다. 감사합니다~!

**Comment by wisdomstar94** [comment]
넵, v1.1.25 배포되었습니다. 명절 잘 보내세요~
