### ISSUE TITLE
목차 및 코드 블럭의 가시성 개선 요청

### ISSUE THREAD

**Issue by kugorang** [wisdomstar94/torytis-tistory-skin-stroke#17]
안녕하세요, v1.1.22 사용 중 개선 사항을 요청드릴 내용이 있어 이슈 남겨놓습니다.

### 목차

- 우측 사이드바에 표기되는 목차 항목에 적용되는 들여쓰기가 h3까지 적용하는 게 가능할지 문의드립니다.
  - 개인적으로는 h4까지 적용되면 좋겠는데, 불가능하다면 h3까지만이라도 부탁드리고 싶습니다.

### 코드 블럭

- python 코드 블럭일 때 코드와 주석이 개인적으로는 잘 보이지 않아 이 부분도 스킨에서 제어가 가능하게 개선할 수 있는지 문의드립니다.
  - ex) 테마: https://code.visualstudio.com/docs/getstarted/themes
  - ex) 글꼴: https://kinsta.com/blog/best-programming-fonts/ or https://github.com/naver/d2codingfont

**Comment by wisdomstar94** [comment]
안녕하세요. 이슈 남겨주셔서 감사합니다.

목차는 h2 일 때 0칸, h3 일 때 1칸 으로 들여쓰기가 되게 되어 있었는데
h4 일 때 2칸 들여쓰기가 되도록 수정할 예정입니다.

그리고 코드에 대한 테마같은 경우는 티스토리의 코드문법강조 플러그인에서 지정해주시는 것이 더 좋을 것 같습니다.
![image](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/assets/93423564/42c87231-c145-4632-9575-945fb1c85ccf)

코드블록에 대한 글꼴 같은 경우는 스킨 옵션에서 폰트 URL 을 입력하여 지정할 수 있도록 작업할 예정입니다.

**Comment by wisdomstar94** [comment]
https://github.com/wisdomstar94/torytis-tistory-skin-stroke/releases/tag/v1.1.24
에서 수정되었으니 확인 부탁드립니다.

**Comment by kugorang** [comment]
안녕하세요, 스킨 적용 후 목차의 들여쓰기는 잘 적용된 것 확인했습니다. 감사합니다 :)

다만, 아직 일부 코드 블럭에서 다크 테마 대응이 되지 않고 있어 이 부분을 확인 부탁드리고 싶습니다.

https://kugora.ng/33 에 적힌 글을 다크 모드로 확인했을 때 화이트 모드로 표시되는 블럭 확인을 부탁드려도 될까요?

<img width="743" alt="image" src="https://github.com/wisdomstar94/torytis-tistory-skin-stroke/assets/12571114/4eb65840-87ae-4857-a9c5-6010bfdc0431">

예시로 "시각적인 설명" 부분을 보시면 될 듯 합니다!

**Comment by wisdomstar94** [comment]
아래에 첨부한 스킨 파일을 적용한 후 확인 부탁드립니다.
이상 없으시면 배포할 예정입니다. :)
[stroke_v1.1.25_test.zip](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/files/14194186/stroke_v1.1.25_test.zip)

**Comment by kugorang** [comment]
안녕하세요, v1.1.25 스킨에서 코드 블럭 버그 해결된 것 확인했습니다!

해결해주셔서 감사하고, 즐거운 설 연휴 되시길 바라겠습니다 :)

**Comment by wisdomstar94** [comment]
넵, v1.1.25 배포되었습니다. 명절 잘 보내세요~
