### ISSUE TITLE
댓글 창의 프로필 이미지 중첩 표시 Issue

### ISSUE THREAD

**Issue by kugorang** [wisdomstar94/torytis-tistory-skin-stroke#19]
안녕하세요, 현재 게시글의 댓글에 포스팅한 사람이 댓글을 남기면 아래와 같이 표기가 되고 있는 상태입니다.

![image](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/assets/12571114/cc43c04c-9f2e-45c1-8185-e9a81c5c9eea)

아이디 위에 있는 작은 프로필 이미지 (파비콘일까요?) 가 두 개 떠 있는데 이 부분에 이슈가 있는지 확인 요청드리겠습니다.

감사합니다.

**Comment by wisdomstar94** [comment]
안녕하세요.
말씀주신 아이디 위에 파비콘 아이콘이 2개 표시되어 있는 현상에 알아본 결과, 티스토리 플러그인 중 "`홈페이지 아이콘 표시(파비콘)`", "`블로그 아이콘 표시`" 플러그인을 동시에 사용하고 계신게 아닌가 추측됩니다. 위 플러그인을 동시에 사용할 경우, 아래 사진 처럼 블로그 관리 페이지에서 등록한 파비콘과 아이콘이 순서대로 표시되게 됩니다.
![image](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/assets/93423564/7e225e0b-d3ff-473d-b046-0483bfd280c9)

2개 아이콘이 표시되는 현상은 위 이유가 아닐까 추측되며, 아이콘이 표시되더라도 아이콘과 사용자 이름이 같은 라인에 보여지도록 수정하였습니다.
![image](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/assets/93423564/d3574817-67bd-4de4-9560-38a7cc7e8809)

[stroke_v1.1.26-test.4.zip](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/files/14814340/stroke_v1.1.26-test.4.zip)

**Comment by kugorang** [comment]
안녕하세요, 해당 부분 수정 완료된 것 확인했습니다! 감사합니다 :)

**Comment by wisdomstar94** [comment]
본 이슈는 닫도록 하겠습니다. 감사합니다.
