### ISSUE TITLE
포스팅 최대 가로 폭 지정 기능 추가 요청

### ISSUE THREAD

**Issue by kugorang** [wisdomstar94/torytis-tistory-skin-stroke#2]
현재 제작자님께서 반응형으로 스킨을 제작해주셔서 감사한 마음을 느끼고 있습니다.

![스크린샷 2023-12-25 13 09 58](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/assets/12571114/37d61ef4-f654-4fb1-b982-3e9fd2de2dbe)

그러나 제가 사용 중인 21:9 모니터에서는 오히려 반응형으로 인해 블로그 글의 가독성이 많이 떨어져 아쉬운 마음이 큽니다. 이를 방지하고자 블로그 스킨 자체의 스킨 편집 기능에서 최대 너비를 고정 시키고자 이것저것 시도를 해봤지만, 무엇을 어떻게 수정해야 할지 감이 안 잡혀 이슈를 남기게 됐습니다.

![스크린샷 2023-12-25 13 03 28](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/assets/12571114/bf79a838-c564-4e34-aaa0-f4f7b58d2231)

현재 네이버 PC 메인 페이지는 가로 폭은 1130px 로 작성되어 있고, 제가 느끼기에도 이 정도면 가독성이 좋다고 생각되어 이 너비에 맞추고자 합니다. 혹시 어렵지 않으시다면 제작자님의 티스토리 스킨 편집 기능에도 이를 추가 부탁드려도 될지 여쭤봅니다.

![스크린샷 2023-12-25 13 03 22](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/assets/12571114/841b5cd9-8b75-4e43-9cdd-1788c4b7c424)

제가 원하는 블로그 폭의 너비입니다. 참고 하시라고 스크린샷 남겨 놓습니다.

감사합니다. 메리 크리스마스 되세요.

**Comment by wisdomstar94** [comment]
안녕하세요. 이슈 남겨주셔서 감사합니다~!

[스킨 편집] -> [블로그 화면 최대 너비 (px)] 의 값을 조정하시면 아래 사진과 같이 
블로그 화면이 표시되는 최대 너비를 지정할 수 있도록 v1.1.4 에서 업데이트 되었습니다.

**-- 1920 기본값 상태**
![image](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/assets/93423564/892d5b54-15eb-46e9-9929-2640e1a0e52a)

**-- 1440 으로 수정한 상태**
![image](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/assets/93423564/56034718-9ed2-4891-8605-02f716361667)

스킨 업데이트 후 옵션에서 너비 값 조정해보시면서 한번 확인 부탁드리겠습니다~
즐거운 크리스마스 되세요~

**Comment by kugorang** [comment]
안녕하세요, v1.1.14 버전 적용한 이후에 해당 기능 추가 및 작동 되는 것까지를 확인했습니다.

감사합니다 :)
