### ISSUE TITLE
이미지 상세보기 기능 지원 

### ISSUE THREAD

**Issue by chani-0** [wisdomstar94/torytis-tistory-skin-stroke#20]
이미지 상세보기 기능 사용시 이미지를 상세보기 닫기가 안됍니다.

**Comment by wisdomstar94** [comment]
안녕하세요. 이슈 남겨주셔서 감사합니다.
아래 정보를 남겨주시면 확인해보도록 하겠습니다.

1. 해당 현상을 확인해 볼 수 있는 블로그 포스트 주소
2. 해당 현상과 관련된 이미지 또는 영상

**Comment by chani-0** [comment]
연락 감사힙니다.
이미지를 첨부하고 여기서 답변을 드리겠스빈다.
[image: image.png]
이미지를 보시면 개발자님의 블로그입니다.
이미지를 클릭하여 상세히 보기로 들어가면 이동, 확대 축소, 회전은 정상적으로 작동됩니다. 하지만 x 표시로 창을 내리려고 하면
내려가지 않습니다.
또한 우측 상단데 x 표시가 하나 뜨고 좌측 상단에는 기존 이미지가 뜹니다.

이것으로 충분한 설명이 되었는 지는 모르겠으나 필요하다면 동영상으로 보내드리겠습니다.
감사합니다.

2024년 6월 28일 (금) 오전 10:39, wisdomstar94 ***@***.***>님이 작성:

**Comment by wisdomstar94** [comment]
@chani-0 
올려주신 이미지가 보이지는 않지만, 제 블로그에 직접 들어가서 확인해보니 해당 현상 확인하였습니다.
티스토리 에서 최근에 [이미지 뷰어 기능](https://notice.tistory.com/2675)이 추가되었는데, 이 기능과 stroke 스킨에서의 이미지 뷰어 기능이 충돌하여 해당 현상이 발생한 듯 합니다.

해당 부분 수정하도록 하겠습니다. 감사합니다.

**Comment by wisdomstar94** [comment]
@chani-0 
안녕하세요. 말씀 주신 부분은 [최신버전](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/releases/latest)에서 수정되었습니다. 확인 후 이상 없으시다면 본 이슈를 닫아주시면 감사하겠습니다.

**Comment by chani-0** [comment]
해당 이슈는 종료된것을 확인했습니다 감사합니다
