### ISSUE TITLE
코드블럭 복사 안됌

### ISSUE THREAD

**Issue by chani-0** [wisdomstar94/torytis-tistory-skin-stroke#21]
해당 스킨이 적용된 사이트는 코드블럭 복사 버튼을 클릭해도 복사가 실해되지않습니다.

**Comment by wisdomstar94** [comment]
@chani-0 
안녕하세요. 이슈 남겨주셔서 감사합니다.
말씀 주신 부분 확인하여 [최신버전](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/releases/latest)에 수정사항이 반영된 상태입니다.

확인 후 이상 없으시면 본 이슈를 닫아주시면 감사하겠습니다.
스킨 이슈 관련하여 적극적으로 제보해주셔서 감사합니다 :)

**Comment by chani-0** [comment]
잘 고쳐졌습니다. 감사합니다.
