### ISSUE TITLE
뒷배경 색상 변경 기능 추가 건의

### ISSUE THREAD

**Issue by JJ-930** [wisdomstar94/torytis-tistory-skin-stroke#22]
안녕하세요, 스킨편집 기능에 배경색 변경 기능을 추가하심이 어떠한지 건의합니다.
(예시로 포스트 인덱스 테두리색을 유저가 직접 색 코드를 넣어서 변경 가능한 것 처럼)

아래는 예시로써, 제 개인 티스토리 뒷배경에(본문쪽) 포샵으로 색을 넣어보았습니다. 
![image](https://github.com/user-attachments/assets/73792671-4522-47ac-b74a-00583d9902b6)

메뉴란, 본문란, 목차란 각각 따로 변경가능하면 좋겠으나, 
일단 본문쪽 배경색을 변경 가능하게 하면 눈의 피로도가 훨씬 줄어 들 것 같습니다.

**Comment by wisdomstar94** [comment]
안녕하세요. 기능 건의 감사합니다.

말씀 주신 기능은 작업 하여 [v1.2.6](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/releases/tag/v1.2.6) 으로 배포하였습니다. 해당 버전으로 적용 후 확인 해주시면 감사하겠습니다. :)

**Comment by JJ-930** [comment]
기능을 추가해주셔서 감사합니다!
라이트모드, 다크모드 모두 변경 해보았고, 각기 다른 색깔로도 해서 적용시켜보았습니다. 현재까진 별 이상없이 작동합니다.

**Comment by wisdomstar94** [comment]
확인 감사드립니다. 본 이슈는 이제 닫도록 하겠습니다. 주말 잘 보내세요.
