### ISSUE TITLE
Google Adsense - Sidebar 문의

### ISSUE THREAD

**Issue by kugorang** [wisdomstar94/torytis-tistory-skin-stroke#23]
안녕하세요, 오랜만에 인사드리네요. 그동안 업데이트 해주셨던 스킨은 현재 잘 사용 중입니다.

Issue를 남기게 된 이유는 이번에 Google Adsense 심사가 통과되어 광고를 붙일 수 있게 되었는데,
스킨에서 사이드바 설정이 작동되지 않아 원래 지원이 안 되는 건지 버그인지 궁금하여 문의드리게 됐습니다.

확인 부탁드리겠습니다. 감사합니다!

**Comment by wisdomstar94** [comment]
@kugorang 
이 글을 이제야 봤네요. ㅠㅠ 늦어서 죄송합니다.

`사이드바 설정이 작동되지 않아` 이 부분이 정확히 어떤 현상인건지 다시 한번 설명 부탁드려도 될까요?

**Comment by kugorang** [comment]
> @kugorang 이 글을 이제야 봤네요. ㅠㅠ 늦어서 죄송합니다.
> 
> `사이드바 설정이 작동되지 않아` 이 부분이 정확히 어떤 현상인건지 다시 한번 설명 부탁드려도 될까요?

안녕하세요 괜찮습니다 ㅎㅎ 첨부해드린 아래 스크린샷을 확인해주시면 감사하겠습니다!

![image](https://github.com/user-attachments/assets/bd136bbf-cc3e-4930-8b26-46230c8b3b2b)

`[광고] adsense` 를 활성화 했음에도 스킨 왼쪽 사이드바에 별다른 변화가 없어 문의드렸습니다.

**Comment by wisdomstar94** [comment]
이 부분은 저도 광고를 활성화 해봐야 확인이 가능할 듯 하네요..!
저도 오늘 구글 애드센스 심사 요청했으니 승인 되는 대로 확인 해보도록 하겠습니다!

**Comment by wisdomstar94** [comment]
@kugorang 
안녕하세요. 생각보다 광고 심사가 빨리 승인되어 금일 확인해보았습니다.
사이드바에 광고가 표시되지 않는 현상은 수정하였고 [최신버전](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/releases/latest)에서 확인해보실 수 있습니다.

한번 확인 부탁드립니다~ (아시다시피 스킨을 변경하면 설정 값들도 모두 초기화되니 최신버전으로 스킨을 교체하신 후 사이드바 설정을 다시 해주신 후 확인해주셔야 합니다!)

**Comment by kugorang** [comment]
안녕하세요, 현재 사이드바에 광고가 잘 표시되는 것 확인했습니다! 감사합니다. :)

이와 비슷한 주제의 문의가 있는데요, 혹시 스킨 편집의 구글 애드센스 URL을 기입하는 곳은 티스토리에서 연동이 문제가 없다면 작성하지 않아도 괜찮을지 여쭤봐도 될까요?

과거에는 헤더 부분에 직접 코드를 넣었으나, 요새는 간소화 된 것으로 알고 있는데 다른 이유로 무조건 기입을 하는 게 좋은가 싶어 질문드립니다.

**Comment by wisdomstar94** [comment]
@kugorang 
넵, 스킨 옵션에 있는 구글 애드센스 url 부분은 티스토리에서 제공하는 연동 기능을 이용하지 않고 순수 직접 연동하고 싶을 때 사용하는 옵션입니다.
이미 모든게 다 정상적으로 동작하고 계시다면 입력하실 필요는 없습니다!

**Comment by kugorang** [comment]
넵 확인했습니다~! 감사합니다 👍

**Comment by wisdomstar94** [comment]
본 이슈는 종료하겠습니다~
