### ISSUE TITLE
글 수정 시간 출력 가능 여부 문의

### ISSUE THREAD

**Issue by kugorang** [wisdomstar94/torytis-tistory-skin-stroke#24]
안녕하세요, 현재 티스토리 블로그 글 작성 시 최초 글 작성 시간은 표시가 잘 되나, 글 수정 시간이 표시 되지 않아 현재는 제가 글 본문에 수동으로 글 수정 시간을 기재 중에 있습니다.

글의 최신화를 알리기 위해 글의 수정 시간을 매번 기재하고 있는데, 혹시 스킨 기능으로 글 수정 시간 출력이 가능하다면 글 작성 시간 바로 밑에 해당 내용이 표시가 되도록 옵션 추가가 가능하실지 문의드립니다.

**Comment by wisdomstar94** [comment]
티스토리 스킨 가이드 문서를 보면 글의 수정 시간 표시에 대한 기능(치환자)은 제공하지 않는 것으로 보여 집니다.

https://tistory.github.io/document-tistory-skin/contents/post.html

**Comment by kugorang** [comment]
안녕하세요, 우선 확인해주셔서 감사하다는 말씀 드립니다. 치환자를 이용해야만 기능 구현이 가능한가 보군요...

방금 간단하게 구글링을 했을 때, 직접 구현 하신 분들의 기록이 남아 있어 혹시 아래의 방법들로 구현하는 건 힘드실지까지만 여쭤봅니다.

- [티스토리 날짜 표시 최종 수정일로 나오게 하는 방법](https://tali.kr/%ED%8B%B0%EC%8A%A4%ED%86%A0%EB%A6%AC-%EC%B5%9C%EC%A2%85-%EC%88%98%EC%A0%95%EC%9D%BC%EB%A1%9C-%EB%82%A0%EC%A7%9C-%ED%91%9C%EC%8B%9C)
- [[ 티스토리 ] 블로그 글의 최종 수정일 가져오기](https://tonks.tistory.com/122)

**Comment by wisdomstar94** [comment]
@kugorang 

아~ dom 요소 중에 관련 정보가 있을 수도 있을 거란 생각은 못해봤네요..
첨부해주신 자료들 보면서 한번 확인해보도록 하겠습니다~!

감사합니다.

**Comment by wisdomstar94** [comment]
[stroke_v1.2.10-test.2.zip](https://github.com/user-attachments/files/17993349/stroke_v1.2.10-test.2.zip)

@kugorang 
위에 첨부한 스킨으로 교체 후 확인 부탁드립니다~ 
수정 된 글이라면 아래 처럼 나와야 정상입니다.
![image](https://github.com/user-attachments/assets/d262e954-c87a-4f22-a40b-5ace2e501f15)

**Comment by kugorang** [comment]
> [stroke_v1.2.10-test.2.zip](https://github.com/user-attachments/files/17993349/stroke_v1.2.10-test.2.zip)
> 
> @kugorang 위에 첨부한 스킨으로 교체 후 확인 부탁드립니다~ 수정 된 글이라면 아래 처럼 나와야 정상입니다. ![image](https://private-user-images.githubusercontent.com/93423564/391976731-d262e954-c87a-4f22-a40b-5ace2e501f15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyODgwODUsIm5iZiI6MTczMzI4Nzc4NSwicGF0aCI6Ii85MzQyMzU2NC8zOTE5NzY3MzEtZDI2MmU5NTQtYzg3YS00ZjIyLWE0MGItNWFjZTJlNTAxZjE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDA0NDk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwMTU4NTI0YTExNjI2MGZiYjAyNjQxMTQ0NjJjMzNiMmQ1MjQzYTAxZDQwMTZjZjM1MTE3OGE4YzgxMDI0MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.O9MpLxjb0yEkJd6KduJ8ZC7-wQt30jnW85aU6J1VpNo)

안녕하세요, 해당 내용이 잘 적용된 것 확인 후에 댓글 남깁니다. 빠르게 대응해주셔서 감사합니다. :)

**Comment by wisdomstar94** [comment]
v1.2.10 배포 되었습니다. 본 이슈는 종료하겠습니다. 감사합니다 :)
