### ISSUE TITLE
홈 커버 표시에 대한 커스터마이징 가능 여부 확인 요청 문의

### ISSUE THREAD

**Issue by kugorang** [wisdomstar94/torytis-tistory-skin-stroke#25]
![image](https://github.com/user-attachments/assets/f25a1007-dca3-45e7-b3bf-b1aa8b6940fa)

안녕하세요, 현재 블로그에 접속하면 표시되는 홈 커버의 각 상자에는 글의 제목과 작성일시, 그리고 본문이 상단부터 표시가 됩니다.

그런데 이번에 수정일시가 추가되기도 하였고, 그 동안 본문 글을 제 임의대로 수정하지 못하여 아쉬움이 있었습니다.

그래서 홈 커버에 나타나는 글 미리 보기를 블로그 주인이 임의대로 수정할 수 있는 기능 추가가 가능할지와 작성일과 수정일 표시도 같이 적용이 가능할지 확인 부탁드리고 싶습니다.

![image](https://github.com/user-attachments/assets/05762f52-8a2a-466f-8403-caa247fb1aca)

간단하게 HTML 수정으로 만들어봤는데, 만약 도입이 가능하다면 수정일은 금방 하시겠지만 커버 안의 글씨를 스킨이 어떻게 감지를 해야 할지 잘 모르겠네요...

특정 기호 또는 인용구를 감싸면 홈 커버 글을 커스터마이징이 되게 하면 좋을 것 같다는 의견이 막 떠올라 남겨봅니다.

어떻게 보면 무리한 부탁이실 수 있어서 어려우시면 그냥 지나치셔도 될 것 같습니다. 항상 감사합니다.

**Comment by wisdomstar94** [comment]
@kugorang 

오히려 이렇게 매번 스킨에 관심 가져주시고 의견 주셔서 감사할 따름입니다. :)

말씀 주신 부분은 한번 확인해보도록 하겠습니다!

**Comment by wisdomstar94** [comment]
@kugorang 

안녕하세요. 

- 홈 화면에 표시되는 글 목록 개별 아이템마다 표시되는 미리보기 글 같은 경우는 티스토리에서 특정 치환자로 내려주고 있는 데이터라서 이걸 본문 글의 특정 지점으로 커스텀 하기는 어려울 듯 합니다.
- 마찬가지로 최근 수정일 또한 상세 페이지와는 달리 dom 요소에서도 접근 할 마땅한 방법이 없는 듯 합니다.

그래서 말씀 주신 부분은 구현이 어려울 듯 합니다..

스킨을 통해 해당 기능을 제공하는 것은 어렵지만 @kugorang 님께서 직접 본인의 본문 글을 아래 방법과 같이 수정하시면 미리보기 글을 내가 원하는 글로 직접 커스텀 하는 것은 가능하실 것 같습니다.

1. 글쓰기 화면에서 html 모드로 들어갑니다.
![image](https://github.com/user-attachments/assets/9f91ce5c-df0d-4709-81a5-d1cd62e86f07)

2. 미리보기 글 내용으로 표시되게 하고 싶은 텍스트를 최 상단에 작성하고 아래 이미지처럼 style="display: none;" 속성을 추가하고 글을 저장합니다.
![image](https://github.com/user-attachments/assets/d923ff52-b175-44a4-a084-1da870641b53)

3. 그럼 아래 사진처럼 홈 화면에선 미리보기용으로만 표시되길 원하는 내용이 표시되며 글 상세화면에서는 해당 내용이 표시되지 않습니다.
![image](https://github.com/user-attachments/assets/67d2e502-42a4-4ec3-af28-47166f47459f)

HTML 모드와 기본 에디터 모드로 전환하면서 서식이 깨지는 경우도 발생할 수 있으니 이점 유의해주세요.

**Comment by kugorang** [comment]
안녕하세요, 먼저 제 요구 사항을 좋게 봐주셔서 감사하다는 말씀 드립니다 :)

하나 건의드리고 싶은 점은 미리보기 글 내용을 커스터마이징할 경우 해당 내용만 나오면 좋을 것 같은데 이 부분이 코드에서 핸들링 되는 부분인지 모르겠네요.

가령 3번에서 "안녕하세요 진짜 첫 시작 글 내용 부분입니다."라는 "display:none"으로 지정된 내용만 미리보기용으로 표시되는 게 사용자 입장으로써 더 직관적이고, 원하는 부분이 될 것 같습니다.

하나 제안드리고 싶은 건 마크다운의 코드블럭(```)을 이용하는 건 어려울까요? 아니면 HTML p 태그 안에 특정 id를 기입하여 해당 id를 미리보기용으로 사용하면 좋을 것 같습니다.

확인 부탁드리겠습니다. 항상 감사합니다!!

**Comment by wisdomstar94** [comment]
@kugorang 

글 미리보기 내용은 티스토리에서 주는 부분이라 이 부분을 스킨에서 어떻게 커스텀 하기는 어렵습니다.

가령 본문 글이 1 ~ 100 의 내용이 있다면 치환자에서 1 ~ 5 부분을 미리보기로 주고 있는 것이기 때문에
스킨에서는 6 ~ 100 에 대한 내용을 아예 참조 할 수 없습니다.

그리고 티스토리에서 주는 글 미리보기 내용은 순수 텍스트로만 구성되어 있습니다.
가령, 글 본문 글의 내용 중 `<p>안녕하세요</p><code>npm i</code>` 이 부분이 미리보기로 내려오면
`안녕하세요 npm i` 이렇게 순수 텍스트로만 오기 때문에 마크다운 문법이나 특정 태그를 활용하는 것도 어려울 것으로 생각됩니다. ㅠ

**Comment by kugorang** [comment]
> @kugorang
> 
> 글 미리보기 내용은 티스토리에서 주는 부분이라 이 부분을 스킨에서 어떻게 커스텀 하기는 어렵습니다.
> 
> 가령 본문 글이 1 ~ 100 의 내용이 있다면 치환자에서 1 ~ 5 부분을 미리보기로 주고 있는 것이기 때문에 스킨에서는 6 ~ 100 에 대한 내용을 아예 참조 할 수 없습니다.
> 
> 그리고 티스토리에서 주는 글 미리보기 내용은 순수 텍스트로만 구성되어 있습니다. 가령, 글 본문 글의 내용 중 `<p>안녕하세요</p><code>npm i</code>` 이 부분이 미리보기로 내려오면 `안녕하세요 npm i` 이렇게 순수 텍스트로만 오기 때문에 마크다운 문법이나 특정 태그를 활용하는 것도 어려울 것으로 생각됩니다. ㅠ

안녕하세요, 이 부분은 확인했습니다. 개인적으로 제목-부제 느낌처럼 글 블록을 꾸미고 싶었는데 아쉽네요 ㅠㅠ

하나만 더 질문드리고 싶은데, 글의 내용 앞 부분 대신 태그가 출력되도록 스킨 옵션을 설정할 수는 없을까요?
그리고 아예 출력하지 않는 기능도 가능할지 확인 부탁드리겠습니다.

마지막 요청이라 위의 두 사항 모두 작업이 힘드시다면 이 이슈는 이후에 Closed로 처리 부탁겠습니다! :)

**Comment by wisdomstar94** [comment]
@kugorang 

안녕하세요. 
말씀 주신 부분은 구현이 가능할 것 같습니다. :)
완료되는 대로 코멘트 드리겠습니다.

**Comment by wisdomstar94** [comment]
@kugorang 

글 목록 페이지에서 글마다 태그가 추가로 표시 되게 되었고
아래 사진처럼 스킨 옵션에서 글 미리보기 내용 또는 태그를 표시하거나 미표시하도록 하는 것이 가능해졌습니다.
![image](https://github.com/user-attachments/assets/b4ac2fb3-42aa-455b-aa27-1706e4548bc1)

아래 파일로 스킨 교체후 확인 부탁드립니다~
[stroke_v1.2.11-test.1.zip](https://github.com/user-attachments/files/18112241/stroke_v1.2.11-test.1.zip)

**Comment by kugorang** [comment]
> @kugorang
> 
> 글 목록 페이지에서 글마다 태그가 추가로 표시 되게 되었고 아래 사진처럼 스킨 옵션에서 글 미리보기 내용 또는 태그를 표시하거나 미표시하도록 하는 것이 가능해졌습니다. ![image](https://private-user-images.githubusercontent.com/93423564/395181193-b4ac2fb3-42aa-455b-aa27-1706e4548bc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4ODA5NjAsIm5iZiI6MTczNDg4MDY2MCwicGF0aCI6Ii85MzQyMzU2NC8zOTUxODExOTMtYjRhYzJmYjMtNDJhYS00NTViLWFhMjctMTcwNmU0NTQ4YmMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIyVDE1MTc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlMWI2MDRkMDU3Mzg3NTc0N2VmNzE5ZGIxZjE2ODRkNzliMDI4NWFlZGMyZDMwODY5YTg5ZTE4MTE2ODNmODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vyfSewV3UHIne10-KAVQVyBTVYa9APz380FV4LCEkLg)
> 
> 아래 파일로 스킨 교체후 확인 부탁드립니다~ [stroke_v1.2.11-test.1.zip](https://github.com/user-attachments/files/18112241/stroke_v1.2.11-test.1.zip)

안녕하세요, 이 부분 문제 없이 잘 작동하는 것 방금 확인했습니다. 감사합니다 :)

**Comment by wisdomstar94** [comment]
@kugorang 
넵 확인 감사드립니다. 본 이슈는 닫도록 하겠습니다.
