### ISSUE TITLE
가로 스크롤 문의

### ISSUE THREAD

**Issue by kugorang** [wisdomstar94/torytis-tistory-skin-stroke#26]
안녕하세요, 그동안 블로그 글을 데스크탑에서 쓰다가 오랜만에 노트북으로 글을 작성하던 중 약간 불편한 UX가 하나 있어 개선이 가능할지 문의 드리려 합니다.

![image](https://github.com/user-attachments/assets/2efe223c-9865-4c3a-987f-3cd684147810)

현재 가로 스크롤이 가능하지 않는 페이지 양식이라 생각됨에도 불구하고, 터치 패드를 통해 가로 스크롤을 하면 일부분이 가로 스크롤 되는 현상이 있습니다.

만약 브라우저에서 핸들링 하는 영역이라 수정이 불가하다면 어쩔 수 없지만, 스킨에서 제어 가능한 부분이라면 가로 스크롤이 불가능하고 세로만 스크롤 되도록 수정 가능 요청을 드리고 싶어 Issue 남깁니다!

**Comment by wisdomstar94** [comment]
@kugorang 

말씀주신 것처럼 가로 스크롤이 원랜 안되야 정상입니다.
해당 부분 확인해보도록 하겠습니다!

**Comment by wisdomstar94** [comment]
@kugorang 

안녕하세요. 
말씀 주신 부분 수정하여 [최신 버전](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/releases/latest)으로 배포한 상태입니다.
스킨을 [최신 버전](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/releases/latest)으로 교체 후 확인 해봐주시면 될 듯 합니다!

그럼 즐거운 크리스마스 보내세요!

**Comment by kugorang** [comment]
> @kugorang
> 
> 안녕하세요. 말씀 주신 부분 수정하여 [최신 버전](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/releases/latest)으로 배포한 상태입니다. 스킨을 [최신 버전](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/releases/latest)으로 교체 후 확인 해봐주시면 될 듯 합니다!
> 
> 그럼 즐거운 크리스마스 보내세요!

감사합니다 :) 현재 제가 문의 드렸던 내용이 모두 잘 수정된 것을 확인했습니다.

작년 이 맘 때 즈음 스킨 문의를 연락 드렸는데 벌써 1년이 흘렀네요.

사용하면서 개인적인 의견으로 건의 사항을 드렸었는데, 그냥 지나치지 않고 하나씩 정성껏 확인 해 주셔서 매번 감사하다는 말씀을 드립니다.

스킨 제작자 님도 좋은 성탄절 되셨기를 바라며, 다가오는 새해에 좋은 일이 많이 일어나길 바랍니다!

**Comment by wisdomstar94** [comment]
시간이 벌써 그렇게 됬군요..! @kugorang 님도 새해 복 많이 받으시길 바랍니다!
