### ISSUE TITLE
최신 버전 안내 창의 최신 버전이 올바르게 표기되지 않음

### ISSUE THREAD

**Issue by kugorang** [wisdomstar94/torytis-tistory-skin-stroke#3]
안녕하세요, 크리스마스인데도 빠르게 대응해주셔서 감사합니다 :) ~혹시 저처럼 솔로이신지 (농담)~

버그가 하나 더 발견되어 이슈 등록해놓습니다.

![image](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/assets/12571114/a9b8566f-8bc3-4a1b-9c2a-b67eda4ed7af)

현재 최신 버전이 1.1.14이나, 1.1.13으로 표기되어 있어 사용자에게 혼란이 있을 수 있을 듯 한데, 만약 시간 차로 인해 발생하는 사소한 이슈라면 넘기셔도 될 것 같습니다.

감사합니다.

**Comment by kugorang** [comment]
그리고 이건 별개의 질문인데 이슈인지는 잘 모르겠어서 연관 내용은 댓글로 남깁니다.

1. 위의 팝업이 스킨 편집에 진입했을 때만 나오는 게 맞는 지 궁금합니다.
2. 현재 "예" 버튼이 안 눌리고 있는데 제가 스킨 편집 창에서 이 창을 보고 있어 그런지 궁금합니다.
3. 마지막으로 스킨 편집이 아닌 그냥 블로그 홈으로 들어가면 이 창이 안 뜨는데 창이 뜨는 조건이 궁금합니다.

**Comment by wisdomstar94** [comment]
안녕하세요. <s>(네, 맞습니다. 솔로입니다 ㅠ)</s>

현재 최신 버전 체크는 "[https://cdn.jsdelivr.net/gh/wisdomstar94/torytis-tistory-skin-stroke/package.json](https://cdn.jsdelivr.net/gh/wisdomstar94/torytis-tistory-skin-stroke/package.json)" URL 에서 반환되는 json 객체의 version 값을 참조하여 이루어지고 있으며, 이는 cdn URL 이므로 github 에 최신 버전이 커밋되었다 하더라도 cdn URL 에 최신 상태로 반영되기 까지는 최대 1일 정도 소요되어 말씀하신 것처럼 시간 차로 발생하는 이슈입니다. :)

또한 블로그 내에서 페이지를 이동할 때마다 버전 체크를 하는 것은 과도하다고 생각되어, 로컬스토리지를 활용하여 마지막으로 버전을 체크한지 5분이 지나지 않은 상태라면 버전을 또 체크하지 않게끔 되어 있습니다. 따라서 스킨 편집 창에서 이미 한번 버전 체크가 이루어진 상태에서 5분이 지나지 않은 채 블로그 홈으로 이동하셨기 때문에 버전 체크 창이 뜨지 않는 것으로 보여집니다. 버전 체크 팝업 창에서 "예" 버튼이 눌리지 않는 것은 말씀하신 것처럼 스킨 편집 창에서 표시되었기 때문에 그런 것 같습니다. (다른 클릭 요소들도 클릭해도 아무런 반응이 없었고 이는 다른 스킨을 적용해도 동일한 것을 확인했습니다.)


1. 위의 팝업이 스킨 편집에 진입했을 때만 나오는 게 맞는 지 궁금합니다.
=> 아닙니다. 블로그 화면이 로드 되었고, 마지막으로 버전을 체크한지 5분이 지났다면 버전 체크 팝업창이 표시됩니다.

2. 현재 "예" 버튼이 안 눌리고 있는데 제가 스킨 편집 창에서 이 창을 보고 있어 그런지 궁금합니다.
=> 그런 것 같습니다. Stroke 스킨뿐만 아니라 다른 스킨도 편집 창에서는 클릭 이벤트가 발생하지 않는 것처럼 보였습니다.

3. 마지막으로 스킨 편집이 아닌 그냥 블로그 홈으로 들어가면 이 창이 안 뜨는데 창이 뜨는 조건이 궁금합니다.
=> 버전 체크는 로그인된 유저가 관리자 계정(블로그 소유자)일 경우에만 진행되고 마지막으로 체크한지 5분이 지난 경우에만 다시 체크가 되므로, 이미 체크된 상태에서 5분내에 홈으로 이동하셨기 때문에 뜨지 않으신 걸로 보입니다.

감사합니다.

**Comment by kugorang** [comment]
넵, 확인해주셔서 감사합니다. 이 이슈는 문제가 없다고 판단되어서 바로 닫도록 하겠습니다.

감사합니다!
