### ISSUE TITLE
블로그 글 본문 중 URL 미리보기가 있을 경우 제대로 출력되지 않음

### ISSUE THREAD

**Issue by kugorang** [wisdomstar94/torytis-tistory-skin-stroke#4]
#1 의 side effect로 보입니다. v1.1.12 -> v1.1.13 에서 업그레이드를 하면 버그가 발생합니다.

![스크린샷 2023-12-25 17 10 13](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/assets/12571114/a16aec77-6b70-4397-b21c-e48df5b2c0a6)

기존 버전 (v1.1.12) 입니다.

![스크린샷 2023-12-25 17 11 36](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/assets/12571114/f1529f1a-13f7-4e02-b70a-5afa8f74da76)

업데이트 버전 (v1.1.13) 입니다.

**Comment by kugorang** [comment]
v1.1.14 에서도 동일한 문제가 발생하는 것을 확인했습니다.

**Comment by wisdomstar94** [comment]
확인 감사드립니다.
v1.1.15 에서 해당 사이드이펙트 수정하였습니다.
[https://github.com/wisdomstar94/torytis-tistory-skin-stroke/releases/tag/v1.1.15](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/releases/tag/v1.1.15)

**Comment by kugorang** [comment]
넵, v1.1.15에서 수정된 것 확인했습니다. 감사합니다! 👍
