### ISSUE TITLE
다크모드 사용자를 위한 시인성 개선 요청

### ISSUE THREAD

**Issue by kugorang** [wisdomstar94/torytis-tistory-skin-stroke#5]
안녕하세요, 제작자님. 이 이슈는 버그는 아니나 다크모드 사용 시 더 나은 UX를 위한 건의 사항입니다.

1. 티스토리에서 자동으로 생성해주는 URL 미리보기가 다크모드에서도 유지되어 제목이 제대로 나오지 않는데 이 부분은 수정이 힘드실지 여쭤봅니다.
 
![스크린샷 2023-12-25 17 44 23](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/assets/12571114/6d3103dc-ed58-4960-8a6a-5cb76e1a1370)

![스크린샷 2023-12-25 17 44 34](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/assets/12571114/57fcac8f-8123-43d9-b9bc-60958cc24ecd)

2. 티스토리의 표 기능을 이용하여 제작한 표의 색상이 다크모드에서는 전부 검정으로 처리되어 고대비처럼 반전 시키면 어떨까 제안드립니다.

![스크린샷 2023-12-25 17 45 08](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/assets/12571114/a3acf159-11bd-4e45-a1b3-604e46fb9e92)

![스크린샷 2023-12-25 17 45 22](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/assets/12571114/1215c127-cc92-41cb-a219-b39a7e673269)

3. 다크모드에서 인용문(blockquote) 기능을 사용한 문장이 일반 문장에 비해 차이점이 별로 나지 않아 이 부분에 대한 개선이 필요합니다.

![스크린샷 2023-12-25 18 23 57](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/assets/12571114/c99135fa-d417-4b2d-9a9d-b2125e9d3235)

![스크린샷 2023-12-25 18 24 05](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/assets/12571114/738a7b28-f0f4-43d7-b039-ee0591710112)

4. 티스토리 플러그인 중 방문자 그래프라는 플러그인이 있는데, 다크모드에서 이 플러그인에서 표기하는 수치가 제대로 나오지 않습니다.

![스크린샷 2023-12-25 19 03 06](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/assets/12571114/6f1bcb3d-d18c-465c-a187-f5a15d5cc028)

![스크린샷 2023-12-25 19 03 17](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/assets/12571114/75872249-ca77-4257-a615-d4e8af5a1cef)

이 이슈는 개인적인 개선 의견이라 필요가 없다고 판단되시면 넘기셔도 됩니다. 감사합니다.

**Comment by wisdomstar94** [comment]
안녕하세요. 
해당 이슈는 v1.1.6 에 반영되었습니다.

자세한 사항은 https://github.com/wisdomstar94/torytis-tistory-skin-stroke/pull/7 을 참고해주시면 되겠습니다.
감사합니다.

**Comment by kugorang** [comment]
안녕하세요, 제작자님. 작업해주신 내용을 모두 확인하고, 질문이 생겨 댓글 남깁니다.

"다크 모드에 맞춰 자동으로 변경될 경우 홀수 번째 행의 border bottom 색상과 짝수 번째 행의 border bottom 색의 차이를 주었습니다." 라고 표기해주신 부분이 구체적으로 어떻게 변경된 건지 자세하게 여쭤봐도 될까요?

다른 사항에 비해 표에 관련된 부분만 수정 사항이 눈에 띄지 않아 문의드립니다.

**Comment by wisdomstar94** [comment]
![image](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/assets/93423564/48c59509-0052-41cb-9f0c-f7a80bfea0ef)
위 사진과 같이 빨간색으로 표시한 홀수번째 행의 <s>border bottom</s> border top 색은 완전 하얀색이며
노란색으로 표시한 짝수번째 행의 <s>border bottom</s> border top 색은 흐린 하얀색으로 변경된 부분입니다.

**Comment by wisdomstar94** [comment]
다시 보니 홀수행의 border-top, 짝수행의 border-top 이 맞네요. 😅

**Comment by kugorang** [comment]
안녕하세요, 어떤 말씀이신지 이해했습니다! 이 이슈는 이대로 종료해도 될 것 같은데, 제가 생각했던 건 다크모드일 때 제목 행 또는 제목 열에 있는 칸의 배경이 회색 등의 처리가 되는 것을 생각했습니다.

Notion의 예시를 가져와봤는데요.

![스크린샷 2023-12-26 19 59 17](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/assets/12571114/83858128-051b-4eee-ac05-1e1e742b70f1)

![스크린샷 2023-12-26 19 58 37](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/assets/12571114/57ebc206-c85d-4c2f-8780-491bde1251e9)

간단한 표 기능에서 위와 같이 표현하고 있어, 이 부분에 대한 시인성 처리는 어떠신지 의견을 여쭤보고 싶습니다! 만약 지금 작업하신 부분만으로 충분하다 여겨지시면 이슈를 닫아도 되실 것 같습니다.

언제나 빠르게 대응해주셔서 감사합니다 🥇

**Comment by wisdomstar94** [comment]
안녕하세요. 
말씀주신 내용을 보고 고민을 해본 후, 화이트 모드일 때 테이블의 기본 스타일 고대비를 최대한 그대로 가져오는 쪽으로 고안해봤습니다.

-- 테이블 스타일 미적용시
(화이트 모드)
![image](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/assets/93423564/b3a5a40e-b80e-4d51-bf62-55c25c81fa8b)

(다크모드(예정))
![image](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/assets/93423564/69085346-3a5c-4c03-bd15-7ae2a098edd4)

-- 테이블 스타일 style1 적용시
(화이트 모드)
![image](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/assets/93423564/38430f3b-6792-4edd-bd2b-1778eba65d71)

(다크모드(예정))
![image](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/assets/93423564/bf9d078b-d36f-4acb-86fe-6cb7a110f573)
--> style2, 3 도 동일

-- 테이블 스타일 style4 적용시
(화이트 모드)
![image](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/assets/93423564/4b042e18-9521-44c6-b680-794be8c7a247)

(다크모드(예정))
![image](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/assets/93423564/b2e45daa-7d45-445f-843c-c76dd313e8a9)
--> style5, 6, 7 도 동일

-- 테이블 스타일 style8 적용시
(화이트 모드)
![image](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/assets/93423564/13306237-b323-408a-b4f1-40d131570185)

(다크모드(예정))
![image](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/assets/93423564/ec5ddc6b-eb55-4826-82b9-bcac9bcb9464)
--> style9, 10, 11 도 동일

-- 테이블 스타일 style12 적용시 
(화이트 모드)
![image](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/assets/93423564/c143c420-abed-4d7f-aae9-a6a9a2c115b2)

(다크모드(예정)) 
![image](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/assets/93423564/4604b476-efb5-49bb-993a-96bebd75079f)
--> style13, 14, 15 도 동일


style1 ~ style15 는 에디터 화면에서 나오는 스타일 목록과 같이 다음과 같습니다.
![image](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/assets/93423564/7d597294-71c4-457c-9c0d-e6adda644fd6)


추가 이견이 없으시면 본 작업 내용을 다음 버전에 반영하려고 합니다.
피드백 부탁드립니다. :)

**Comment by kugorang** [comment]
와.. 제가 생각했던 거 보다 더 좋은 방안을 생각해주셨네요.. 고민 많이 하신 흔적이 보여서 너무 감사합니다

이견 없습니다! 의견 반영해주셔서 감사합니다 :)

**Comment by wisdomstar94** [comment]
v1.1.17 에 반영 되었습니다.

**Comment by kugorang** [comment]
안녕하세요, v1.1.17에 반영되어 기능 잘 동작하는 것까지 확인했습니다. 감사합니다 :)
