### ISSUE TITLE
행간 설정 기능 추가 요청

### ISSUE THREAD

**Issue by kugorang** [wisdomstar94/torytis-tistory-skin-stroke#6]
안녕하세요, 제작자님. 블로그 글을 수정하던 중 행간을 수정하려 했으나 이에 대한 옵션이 없어 문의드립니다.

![스크린샷 2023-12-25 19 44 38](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/assets/12571114/7cfdfe77-992f-4530-8f9d-c69b96d2676f)

티스토리의 기본 에디터만큼 행간을 주면 좋겠으나,

![스크린샷 2023-12-25 19 45 10](https://github.com/wisdomstar94/torytis-tistory-skin-stroke/assets/12571114/01ac5128-119b-45b8-beb1-70944a98b611)

스킨의 기본 설정으로 조금 좁아진 느낌이 들어 이를 늘려보고자 했으나 역시 실패해서 이슈를 남기게 됐습니다.

----

스킨 편집에서 글 전체의 행간 수치를 설정하게 하도록 옵션 추가를 하는 등의 개선은 어려우실지 여쭤봅니다. 감사합니다!

**Comment by wisdomstar94** [comment]
안녕하세요.
해당 이슈는 v1.1.6 에 반영되었습니다.

자세한 사항은 https://github.com/wisdomstar94/torytis-tistory-skin-stroke/pull/8 을 참고해주시면 되겠습니다.
감사합니다.

**Comment by kugorang** [comment]
안녕하세요, 해당 부분이 v1.1.16에서 잘 반영된 것을 확인했습니다. 감사합니다 :)
